#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: C:/sell.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.106.158.206:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
  port: 8090