#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: C:/sell.log

spring:
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.106.158.206:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null


server:
  servlet:
    context-path: /sell
  port: 443
  ssl:
    key-store: 1.pfx
    key-store-password: RnRi10q0






